service: retro-ko-scraper

provider:
  name: aws
  runtime: python3.7

functions:
  retroKoScraper:
    handler: handler.run
    events:
      - schedule:
          rate: cron(*/30 * * * ? *)
          enabled: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
